version: "3"
volumes:
  prometheus_data: {}
  
services:

  eureka-naming-server :
    image: eureka-naming-server
    ports:
      - "8761:8761"
    networks:
      - test-network


  stock-service:
    image: stock-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://localhost:8761/eureka
        -DZIPKIN_SERVER=http://localhost:9411/
    ports:
      - "9003:9003"
    #    links:
    #      - zipkin
    depends_on:
      - eureka-naming-server
    #      - zipkin
    networks:
      - test-network


  enquiry-service:
    image: enquiry-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://localhost:8761/eureka
        -DZIPKIN_SERVER=http://localhost:9411/
    ports:
      - "9004:9004"
    #   links:
    #     - zipkin
    depends_on:
      - stock-service
    #     - zipkin
    networks:
      - test-network


  cloud-api-gateway-service:
    image: cloud-api-gateway-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://localhost:8761/eureka
        -DZIPKIN_SERVER=http://localhost:9411/
 #       -DENQUIRY_SERVICE=http://techefx-product-enquiry-service:9700/
    ports:
      - "9002:9002"
    #   links:
    #     - zipkin
    depends_on:
      - eureka-naming-server
      - stock-service
      - enquiry-service
    #      - zipkin
    networks:
      - test-network


  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/:/etc/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=31d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    depends_on:
      - techefx-product-stock-service
    networks:
      - test-network


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - test-network


  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    depends_on:
      - techefx-eureka-namng-service
    networks:
      - test-network



networks:
  test-network:

